### ISSUE TITLE
Best practices for multi-paper study?

### ISSUE THREAD

**Issue by nsunami** [cjvanlissa/worcs#113]
What are some best practices for using WORCS for multi-study paper? I'm trying to incorporate WORCS for a project with 3 studies. I can imagine doing this in three ways:

1. Creating separate WORCS project for each study
2. Creating multiple preregistrations within one WORCS project
3. Putting information about 3 studies in one preregistration in one WORCS project

I'm thinking of going with option 3 since it does not change the structure of the WORCS. If anyone has any recommendations, please let me know.

**Comment by cjvanlissa** [comment]
I believe there is no overwhelming preference for any of the three. For my convenience, I would probably go with 3 if the studies are intended for the same paper, and 2 if the studies are intended for 3 different papers. Good luck!

**Comment by nsunami** [comment]
Got it. Thank you!
