### ISSUE TITLE
Question on 2 choices made in installation guide

### ISSUE THREAD

**Issue by bmkramer** [cjvanlissa/worcs#119]
In going over the [setup vignette](../blob/master/vignettes/setup.Rmd) in preparation for the WORCS workshop, I came across two points:

- Step 4 - Register on Github, step 2: Request a free academic upgrade to be able to create private repositories - currently, all users are able to create private repositories (with some limits on functionalities, but nothing that will affect anything described in the WORCS workflow as far as I am aware?) - see [here](https://github.blog/2019-01-07-new-year-new-github/) and [here](https://docs.github.com/en/get-started/learning-about-github/githubs-products))

I would suggest not to include this step in the installation guide for first users

- Step 6 - run `worcs::git_user("your_name", "your_email", overwrite = TRUE)`

What's the reason to force overwrite = TRUE rather than the default overwrite = FALSE to not overwrite existing Git credentials?

**Comment by cjvanlissa** [comment]
Dear Bianca,
I will change Step 4 due to GitHub's changed policy.

Step 6 is necessary, otherwise they will not have a valid git user and all git-related functions will fail. Overwrite = FALSE just does nothing, it's to ensure that our package tests don't change people's git users all around the world.

**Comment by bmkramer** [comment]
Hi Caspar, thanks for your reply. 

Re: step 6: sure, but if a user has already set their git credentials, why is there a need to overwrite them in this step? (sorry if I'm being dense here ;)

**Comment by cjvanlissa** [comment]
This is a tutorial for starting from scratch; as it says in the intro, if a user already has some of this software installed, they can skip those steps.

But given the fact that not having a git user was one of the most common problems in workshops pre-worcs, I don't think it's wise to remove this step.
