### ISSUE TITLE
Include citation file

### ISSUE THREAD

**Issue by kequach** [cjvanlissa/worcs#122]
I was reading the WORCS publication and noted that this repository follows FAIR Principles. When running the command line tool I noticed that this repository only fulfills 4 out of 5 points because of the way citations are checked:
![image](https://user-images.githubusercontent.com/18238845/163605543-11fceb4b-1e40-47ed-a890-002a344b9d7f.png)
In order to fulfill this, the easiest way would be to add a citation file. You can find information about this here: https://citation-file-format.github.io/
I am happy to help if you have any questions. This is the tool used for measuring this: https://github.com/fair-software/howfairis

**Comment by cjvanlissa** [comment]
This is out of scope, CFF is primarily for software (original code) and WORCS is for scientific papers.

**Comment by aaronpeikert** [comment]
Not that this concerns me, however, I disagree. I guess @kequach means this particular repository (the WORCS software) which could use a CFF file for convenience. Whether or not it is desirable for WORCS projects, in general, is another matter.

**Comment by cjvanlissa** [comment]
@aaronpeikert I see! I think this is done now
