### ISSUE TITLE
Check WORCS function

### ISSUE THREAD

**Issue by swvanderlaan** [cjvanlissa/worcs#128]
I am running the `check_worcs_installation()`-function but get an error like below. 

_How I can I fix this?_ 

```
worcs::check_worcs_installation()
Error in libgit2::git_repository_open_ext : 
  could not find repository from '/Users/USERNAME'
✔ dependencies
✔ git
✔ github
✔ renv_consent
✔ rmarkdown
✔ tinytex
```

(I replaced my _real_ username with a dummy one.)

**Comment by cjvanlissa** [comment]
it means that your current folder is not a git repository... if that is as intended, then it doesn't matter!
