### ISSUE TITLE
export_project() not working on Linux (mac unknown)

### ISSUE THREAD

**Issue by cjvanlissa** [cjvanlissa/worcs#20]
The tests in https://github.com/cjvanlissa/worcs/blob/master/tests/testthat/test-export_project.R are currently enabled for Windows only, because testing on other systems gives errors. I'm at a loss on how to solve these - maybe @aaronpeikert could you have a look?

**Comment by aaronpeikert** [comment]
So it works on my machine:
```
R version 3.6.3 (2020-02-29)
Platform: x86_64-solus-linux-gnu (64-bit)
Running under: Solus 4.1 Fortitude
```
I'll investigate why they fail on travis.

**Comment by brandmaier** [comment]
I can confirm that it works on my macOS version:

```
R version 4.0.0 (2020-04-24) -- "Arbor Day"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin17.0 (64-bit)

```
