### ISSUE TITLE
Examples in citation.R give NOTE on package check

### ISSUE THREAD

**Issue by cjvanlissa** [cjvanlissa/worcs#21]
Here is my email to Uwe Ligges, explaining the issue. I've spent two days debugging it and cannot get any further. Maybe @aaronpeikert has an idea?

I’m emailing you about an issue you have previously addressed here: https://www.mail-archive.com/r-package-devel@r-project.org/msg04279.html

As outlined in the CRAN policies, I use tempdir() for examples that require writing files, and I attempt to clean this location afterwards. However, no matter if I use unlink() or file.remove(), the package check gives the NOTE of “non-standard things in the check directory”.

There is an example of such a test below, along with the resulting NOTE. I have tried different ways to clean the temporary files, including using tempdir() instead of tempfile(), and using unlink() only, or file.remove() only.

How should I properly clean up the tempdir?

```
# Create temporary filename
file_name <- tempfile("citeessential", fileext = ".Rmd")
# Write file
rmarkdown::draft(file_name,
                 template = "github_document",
                 package = "rmarkdown",
                 create_dir = FALSE,
                 edit = FALSE)
# Render Rmarkdown
cite_essential(file_name, "UTF-8")
# Cleanup
file.remove(c(
  file_name,
  gsub("\\.Rmd", "\\.md", file_name),
  gsub("\\.Rmd", "\\.html", file_name)
))
unlink(gsub("\\.Rmd", "_files", file_name), recursive = TRUE)


> checking for non-standard things in the check directory ... NOTE
  Found the following files/directories:
    'citeessential49b82dda6a8a.Rmd' 'citeessential49b82dda6a8a.html'
    'citeessential49b82dda6a8a.md' 'citeessential49b82dda6a8a_files'
```

**Comment by cjvanlissa** [comment]
I've also tried tempdir() instead of tempfile(). Didn't make a difference...

**Comment by aaronpeikert** [comment]
You seem to do everything correctly, e.g. the `help(read.csv)` has this example:
``` r
test1 <- c(1:5, "6,7", "8,9,10")
tf <- tempfile()
writeLines(test1, tf)

read.csv(tf, fill = TRUE) # 1 column
ncol <- max(count.fields(tf, sep = ","))
read.csv(tf, fill = TRUE, header = FALSE,
         col.names = paste0("V", seq_len(ncol)))
unlink(tf)
```
So I am clueless why this happens. My only suggestions is to wrap this example in `\dontrun{}`...

**Comment by cjvanlissa** [comment]
Maybe some way the file names are handled? \dontrun{} will be rejected by the CRAN team.

**Comment by brandmaier** [comment]
When you prepare arguments for the `render()` here:
```  
Args <- list(
    input = bn,
    encoding = encoding
  )
```

Maybe you can populate this with extra arguments that build the temporary files explicitly in a different location? It seems there are arguments `intermediates_dir` or `knit_root_dir` to do the job?

**Comment by cjvanlissa** [comment]
Unfortunately I don't think that's it: All of the intermediate files are correctly cleaned up, and the default behavior of knit_root_dir is to knit to the root dir where the .Rmd lives. At least that part is working, because both the .Rmd and the knitted files all end up in the wrong place :( 

> intermediates_dir	
> Intermediate files directory. If a path is specified then intermediate files will be written to that path. If NULL, intermediate files are written to the same directory as the input file.
> 
> knit_root_dir	
> The working directory in which to knit the document; uses knitr's root.dir knit option. If NULL then the behavior will follow the knitr default, which is to use the parent directory of the document.

**Comment by cjvanlissa** [comment]
I also noticed that rmarkdown::draft() returns the location of the file after creating it. That also says that they are in tempdir()!

**Comment by aaronpeikert** [comment]
So If I run it on my pc, I get files that are **not** in the tempdirs where they should be. I think Andreas is on the right track.

**Comment by cjvanlissa** [comment]
This commit  fixes it, but WHY 5e23f0b62283d64d45abc93431cdd29659296130

**Comment by aaronpeikert** [comment]
I think because your citeall funktion has side effects which are changed by setting the working directory.

**Comment by aaronpeikert** [comment]
https://github.com/cjvanlissa/worcs/blob/5e23f0b62283d64d45abc93431cdd29659296130/R/citations.R#L110
Is a bn is a relative path depending on your working directory isn't it?

**Comment by cjvanlissa** [comment]
F88888k you've got it

**Comment by aaronpeikert** [comment]
I am meanwhile in the process of rewriting it..

**Comment by aaronpeikert** [comment]
OK too tired now, I will continue tomorrow.
