### ISSUE TITLE
License Issue

### ISSUE THREAD

**Issue by aaronpeikert** [cjvanlissa/worcs#23]
worcs uses GPL, repro MIT license
May I copy code from [worcs](https://github.com/cjvanlissa/worcs/) to [repro](https://github.com/aaronpeikert/repro/)?

**Comment by cjvanlissa** [comment]
Yes, if I stick with GPL you can consider any such action as if it were a direct contribution from me to repro, as long as I am listed as contributor.

Would you strongly recommend that I switch to MIT, or is this sufficient?

**Comment by aaronpeikert** [comment]
Great. That is sufficient, I do not see a reason for you to switch (but neither do I see a reason for repro, I choose MIT because it is easier for companies to use in case they use repro to move their analysis to production).
