### ISSUE TITLE
Package functions cannot find package data

### ISSUE THREAD

**Issue by cjvanlissa** [cjvanlissa/worcs#27]
I included a package data file `worcs_checklist`, and I'm trying to call it by name inside `worcs_badge()`.

This gives a NOTE:

```
> checking R code for possible problems ... NOTE
  check_worcs: no visible binding for global variable 'worcs_checklist'
  Undefined global functions or variables:
    worcs_checklist
```

**Comment by cjvanlissa** [comment]
At least it does not complain now.. but what is the proper solution?
2476c9df628a7c9b77ebdc55831fe419abbc6335

**Comment by aaronpeikert** [comment]
Could you direct me to the commit which introduces this note?

**Comment by cjvanlissa** [comment]
80b9d12872452a85aac7a36ec282220eed02a1c9

**Comment by aaronpeikert** [comment]
Have you used `devtools::use_data` or did you do it manually?
More generally did you follow the steps in:
http://r-pkgs.had.co.nz/data.html
If yes, I investigate, if not please look again if these resources help...

**Comment by cjvanlissa** [comment]
I don't use use_data; I include them as .csv because these are both human and machine readable. Yes, I have read that article (didn't help).

**Comment by aaronpeikert** [comment]
Actually I think 2476c9d *is* the proper solution, other packages do the same:

https://github.com/cwickham/munsell/blob/e5395412df13d1a4dc9da4a3eab2bbce50a64e34/R/munsell.r#L15

Do you have any reason to believe it is not correct to use `globalVariables`?

**Comment by cjvanlissa** [comment]
Well, since worcs_checklist is exported from the namespace just like any other function, it's strange to me that it would not be visible inside the namespace as well :(
