### ISSUE TITLE
cite functions no longer handle relative paths to resources

### ISSUE THREAD

**Issue by cjvanlissa** [cjvanlissa/worcs#34]
@aaronpeikert , is it possible that this broke with your fix to the citation functions? E.g., the WORCS manuscript no longer knits because it cannot find images in the same folder.

**Comment by aaronpeikert** [comment]
Oh I am sorry. I'll add a test and a fix today.

**Comment by cjvanlissa** [comment]
I fixed the file path issue.. but the umlaut in universität is now also giving an error, because the file is no longer read as UTF-8... what should we do?

**Comment by aaronpeikert** [comment]
Sorry I missed that not only knitr does need to know the encoding but also readlines.

**Comment by cjvanlissa** [comment]
Possibly related: The figure in our manuscript is no longer recognized as such. It does print to PDF, but it's no longer placed below the text, and the cross-reference to this figure fails.

```
Warning message:
LaTeX Warning: Reference `fig:scholarbib' on page 13 undefined on input line 27
1.
LaTeX Warning: There were undefined references. 
```

**Comment by aaronpeikert** [comment]
What I don't understand is why you can just overwrite the original file:
https://github.com/cjvanlissa/worcs/blob/0ffe84374adba3fb2558311a210565d3f72bf6f8/R/citations.R#L64-L69

**Comment by cjvanlissa** [comment]
I don't understand what you mean. Are you saying we should create a temp file in the same directory and render that, then remove it?

**Comment by cjvanlissa** [comment]
Here's another idea:
1) Rename the original
2) Write temp file with same name as original
3) Delete temp file
4) Rename original back

**Comment by aaronpeikert** [comment]
What I do not understand, is how if you use `cite_all` the double @ are retained?
So I have a markdown with:

`Optional reference: @@reference2020`

then knit it using cite_all, doesn't it change permanently to:

`Optional reference: @reference2020`

**Comment by aaronpeikert** [comment]
> Here's another idea:
> 
> 1. Rename the original
> 2. Write temp file with same name as original
> 3. Delete temp file
> 4. Rename original back

That should do the trick.

**Comment by aaronpeikert** [comment]
OK no, I have not understood your code fully! Overlooked:
https://github.com/cjvanlissa/worcs/blob/0ffe84374adba3fb2558311a210565d3f72bf6f8/R/citations.R#L74

**Comment by cjvanlissa** [comment]
Yes. I'm temporarily overwriting the Rmd file after removing the double @@. It's a hack, but it's also the easiest way to ensure rmarkdown can process the file as normal.

**Comment by aaronpeikert** [comment]
I actually like this solution more than using temporary files...
I think generally that now umlaute and relative paths should work, however, maybe you can take a look at #38 ?
