### ISSUE TITLE
Ready for CRAN?

### ISSUE THREAD

**Issue by cjvanlissa** [cjvanlissa/worcs#43]
My CRAN tests are passing; are we ready to submit?

**Comment by aaronpeikert** [comment]
I'll check again on [r-hub](https://r-hub.github.io/rhub/articles/rhub.html) if it is working everywhere.

**Comment by cjvanlissa** [comment]
Rhub is a mess lately.. for 3 of my packages, I get PREPERRORs :/

**Comment by aaronpeikert** [comment]
OK as not maintainer you cannot run the checks on r-hub. But on my machine, the check works perfectly.

**Comment by cjvanlissa** [comment]
The export test is still failing on r-hub (on the only platform that doesn't give a preperror). I'm adding a conditional to this test: Only run it if a single text file can be successfully zipped on the testing system.

**Comment by cjvanlissa** [comment]
Yeah, that really helps.

**Comment by cjvanlissa** [comment]
@aaronpeikert I want to avoid masking `usethis::git_credentials()`. How about `worcs::git_user()`?

**Comment by aaronpeikert** [comment]
Yes, that is a lot better.

**Comment by aaronpeikert** [comment]
``` r
sessioninfo::platform_info()
#>  setting  value                       
#>  version  R version 3.6.3 (2020-02-29)
#>  os       Solus 4.1 Fortitude         
#>  system   x86_64, linux-gnu           
#>  ui       X11                         
#>  language (EN)                        
#>  collate  en_US.UTF-8                 
#>  ctype    en_US.UTF-8                 
#>  tz       Europe/Berlin               
#>  date     2020-05-12
```

<sup>Created on 2020-05-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by brandmaier** [comment]
```r
sessioninfo::platform_info()
 setting  value                       
 version  R version 4.0.0 (2020-04-24)
 os       macOS Mojave 10.14.6        
 system   x86_64, darwin17.0          
 ui       X11                         
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       Europe/Berlin               
 date     2020-05-12  
```
