### ISSUE TITLE
Discuss how worcs meets FAIR principles

### ISSUE THREAD

**Issue by cjvanlissa** [cjvanlissa/worcs#45]
Findable
Accessible
Interoperable
Reusable

These apply to more than just the data

**Comment by bvreede** [comment]
Right, this should probably be done today, no? I don't think I can manage today [very busy schedule...] — but tomorrow should be fine.

**Comment by cjvanlissa** [comment]
@bvreede I'm happy to wait for your excellent contributions :) @annalenalamprecht is looking at it today (it's one of her research areas), and then you and I can do a second pass tomorrow!

**Comment by bvreede** [comment]
Perfect! Thanks @annalenalamprecht :)

**Comment by cjvanlissa** [comment]
@bvreede @annalenalamprecht can you see if the current version does this adequately?
