### ISSUE TITLE
worcs package citation

### ISSUE THREAD

**Issue by brandmaier** [cjvanlissa/worcs#52]
Is this the preferred citation of the worcs package?

@Manual{,
    title = {worcs: Workflow for Open Reproducible Code in Science},
    author = {Caspar J. {van Lissa}},
    year = {2020},
    note = {R package version 0.1.1},
    url = {https://CRAN.R-project.org/package=worcs},
  }

**Comment by brandmaier** [comment]
This is the result of `citation("worcs")`. Maybe add an explicit CITATION file that allows references the preprint?

**Comment by cjvanlissa** [comment]
Huh!?? I thought `citation()` took its info from DESCRIPTION... do you know what's going wrong here?

BTW: I intend to fix this before the preprint is released, so should be fixed before people start using it.

**Comment by brandmaier** [comment]
I wasn't sure what the intended behavior was :-) If the preferred citations includes all contributors (which I would appreciate a lot, of course), then one probably needs a CITATION file. I assume that `citation()` only parses persons with role _author_ but not _contributor_.

**Comment by brandmaier** [comment]
anyway,  it's fantastic that you can do `install.packages("worcs")` now!

**Comment by cjvanlissa** [comment]
This is a big oversight. I'll get on to fixing it, and I'm sorry.

**Comment by cjvanlissa** [comment]
Addressed by commit 032bd46ff863e342cf7684a7e985079e4ee51e30
