### ISSUE TITLE
Should worcs_project generate .RProj file if called interactively AND it does not exist?

### ISSUE THREAD

**Issue by cjvanlissa** [cjvanlissa/worcs#56]
Probably not - might interfere with RStudio functioning

**Comment by brandmaier** [comment]
I assume this has potential for side-effects if we manually create those. If at all, let's use the  `usethis` package:

```{r}
usethis::use_rstudio()
```

**Comment by cjvanlissa** [comment]
@brandmaier I accidentally tagged you, but thank you for chipping in :) I agree. I opened this issue mostly to keep track of enhancements that have been considered, but I think the risk/reward of this enhancement is not very favorable.

**Comment by aaronpeikert** [comment]
Hope you do not mind if I chip in too. I think it is not worthwhile to invest much effort into an automated mechanism that converts any analysis into `worcs`. There are many degrees of freedoms and edge cases we'd need to consider and we'd need not only to detect them but make smart decisions for the user.

Don't get me wrong, users who started an analysis and now want to make it reproducible are an important target group.

**Comment by cjvanlissa** [comment]
Totally agree!
