### ISSUE TITLE
Figure references in the text are not found

### ISSUE THREAD

**Issue by cjvanlissa** [cjvanlissa/worcs#58]
@aaronpeikert @brandmaier maybe you guys know what's happening here...

The Figure in the text is no longer recognized as such; it's printed in the middle of the page as a float, instead of at the end of the manuscript, and the `\@ref()` code is no longer detected. It's really doing my head in...

https://github.com/cjvanlissa/worcs/blob/399fa96db31c30e39f4538a916c38c41b3aa3376/paper/Manuscript.Rmd#L536

**Comment by cjvanlissa** [comment]
I really have no clue how to fix this... anyone? :(

**Comment by cjvanlissa** [comment]
This is solved by 3c02206

Figures must have a `fig.cap = ""`

**Comment by aaronpeikert** [comment]
A nice... Sorry for not being any help.
