### ISSUE TITLE
add compatibility with other software platforms (e.g. gitlab)

### ISSUE THREAD

**Issue by bvreede** [cjvanlissa/worcs#61]
Given the variety of advantages and disadvantages related to the main software platforms, I believe it would be nice if worcs was platform-agnostic for the remote git repository.

Right now, github is explicitly mentioned:
- in the paper
- in the dialog when setting up a worcs project
- in the confirmation checklist when setting up a worcs project

More importantly, a gitlab address is not accepted when setting up a worcs project; neither in the function `worcs_project()` nor through the new project dialog. (I have not tested bitbucket.) I was able to connect a remote gitlab repo only through explicit action after doing the worcs project setup.

The `worcs_badge()` function and the `worcs_checklist` are more agnostic; they mention a "remote repository (e.g. GitHub)", but do not mandate the use of GitHub.

I think it is worth adding functionality for the immediate inclusion of GitLab and Bitbucket in the setup of a worcs project, and changing the language in places so it is more platform agnostic.

**Comment by cjvanlissa** [comment]
@bvreede in the revised manuscript, it is explicitly mentioned that `worcs` (package) works with GitLab and Bitbucket. Version 0.1.2 should work with both of those, and has a vignette on how to connect them - so let me know if you're still experiencing problems.
In terms of being more platform agnostic in the paper - I disagree. One of the main goals of WORCS is to give sensible default choices for many hard decisions, and as the overwhelming majority of Git users are on GitHub, I think there's no contest there.

**Comment by bvreede** [comment]
Thanks @cjvanlissa! I agree with you on making some choices for the user, though for me language like "e.g. GitHub" would be sufficient here; we provide the example and explain the workflow with GitHub, but it is eventually up to the user whether they choose GitHub, or go with GitLab or Bitbucket instead. Personally, I have my issues with GitHub, which makes me a reluctant user sometimes, so advocating for the platform can feel somewhat disingenuous, but then again your point stand: it is the main platform for git users so it makes sense to direct people here. (And I do this in the RepCo course as well... so yeah.)

Regarding compatibility: it's not working for me just yet. At this moment, I have the latest version installed from github (`worcs_0.1.2.1`). My gitlab repo address is not accepted:
```
X  No valid 'GitHub' address provided. You are working with a local 'Git' repository only.
```
I have tried both through the `worcs_project()` function and the new project dialog route, and both give the same result.

**Comment by bvreede** [comment]
OK, I figured out the problem! The HTTPS address given by gitlab does not end in .git; when I add this it works!

**Comment by bvreede** [comment]
OK, have meanwhile figured out that part of the problem was my own fault: the https-URL provided by gitlab (namely: none; so I used the URL in the browser) does not have a .git extension, so it automatically fails with above error message.

The SSH address also fails (but that is the one I would use when connecting a gitlab repository on the command line) immediately with the same error message.

When adding .git to the URL from the browser, the project takes a long time to set up, and eventually asks for the gitlab user name and password, but fails when this is provided. So it's not the error I thought it had, but still does not work for me.

(My gitlab does not have dual authentication, which could be a culprit, but shouldn't be in this situation.)

**Comment by cjvanlissa** [comment]
This is why I suggest people use GitHub ;)

**Comment by cjvanlissa** [comment]
Kidding/not kidding. With GitHub and the instructions in the paper/vignette, I'm confident that 90% of people can get it to work. With GitLab/Bitbucket.... no clue
