### ISSUE TITLE
Bibtex reference to the worcs paper is outdated

### ISSUE THREAD

**Issue by bvreede** [cjvanlissa/worcs#62]
In the dummy reference bibliography that is created when generating a new worcs project, a reference to the worcs paper is placed. This citation information is outdated, and also contains file path information to @cjvanlissa's own system, I believe:

```
@article{vanlissaWORCSWorkflowOpen2020,
  title = {{{WORCS}}: {{A Workflow}} for {{Open Reproducible Code}} in {{Science}}},
  shorttitle = {{{WORCS}}},
  author = {Van Lissa, Caspar J. and Brandmaier, Andreas M. and Vreede, Barbara and van de Schoot, Rens and Brinkman, Loek},
  year = {2020},
  month = feb,
  publisher = {{OSF}},
  doi = {10.17605/OSF.IO/ZCVBS},
  abstract = {Hosted on the Open Science Framework},
  file = {C\:\\Users\\lissa102\\Zotero\\storage\\4A72PMFS\\zcvbs.html},
  language = {en}
}
```

**Comment by cjvanlissa** [comment]
I'm going to try to have this update automatically when the package is built. @brandmaier , can I use the Makefile somehow to run an R script when clicking "Build"?

**Comment by aaronpeikert** [comment]
Yes you can run a R-script with make. In my experience `Rscript -e 'source("some_script.R")` is the easiest way.
