### ISSUE TITLE
visual summary of worcs project

### ISSUE THREAD

**Issue by bvreede** [cjvanlissa/worcs#65]
I've been playing with a visualization of worcs; initially I wanted to visualize the workflow, but what I have so far is a summary of a worcs project. I'm at a point where I'd like some feedback before I proceed, so this is what I have so far:

![image](https://user-images.githubusercontent.com/5747405/83075457-3095de00-a074-11ea-86b6-ccf0d8cbec5e.png)

Questions
- are there missing elements? (e.g.: `.worcs`/YAML file; bibliography;...)
- perhaps elements that are too prominent (e.g. preregistration document?) that are not a part or should not be a part of this summary
- ideas for elaborating into a workflow?
- should workflow be a separate visualization?

... other ideas/comments? I'll still likely be playing a lot with the actual visuals -- though comments on that: also much appreciated.

**Comment by aaronpeikert** [comment]
We (@brandmaier and I) had the same idea for another closely related [paper](https://github.com/aaronpeikert/reproducible-research). But yours is just much more aesthetically pleasing, looks really beautiful! Just in case you haven't seen it, our (in comparison crappy) our attempt:
![nutshell](https://user-images.githubusercontent.com/29424409/83123960-d88fc380-a0d5-11ea-9d51-71682f7a26ce.png)

**Comment by brandmaier** [comment]
This is fantastic, @bvreede. I think we need both: visualizations of the workflow (or, different aspects of it) and such overview slides! 
Only a minor comment: is "environment" clear enough or should it be "software environment" or "package environment" for those less familiar with the meaning of the hexagon in the R community.

**Comment by cjvanlissa** [comment]
I would prefer that we use "dependencies" instead of environment, as that's what we're using in the paper!

**Comment by bvreede** [comment]
@cjvanlissa — I like dependencies too, and an extra +1 for linking terms to the paper!
@brandmaier and @aaronpeikert — cool, this is so useful! (I think I would prefer a live whiteboarding session, but I'll take this :)) I'll try and mix my graphic up a bit to get a bit closer to your workflow. This is the one for `repro`, though, correct?

I like that we have the same way of showing history! I actually played around with that a lot and wasn't sure if this was the best way to show it. Reassuring to see others get to the same conclusion :)

**Comment by cjvanlissa** [comment]
I think this relates to the above images, so I'll share it here: First draft of the visual representation of the workflow.

https://imgur.com/37JB6OW

**Comment by bvreede** [comment]
Wow, that looks awesome!
