### ISSUE TITLE
LaTeX failed to compile

### ISSUE THREAD

**Issue by brandmaier** [cjvanlissa/worcs#67]
I just pulled the latest version and tried to build the paper by running

```{r}
Rscript -e 'rmarkdown::render("Manuscript.Rmd")'
```

This yields:

> 
> ! Argument of \@sect has an extra }.
> <inserted text> 
>                 \par 
> l.176 
> 
> Error: LaTeX failed to compile Manuscript.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See Manuscript.log for more info.
> Execution halted

Any ideas?

**Comment by aaronpeikert** [comment]
It is something in the title. Works for me with title "Test".

**Comment by aaronpeikert** [comment]
Latex doesn't allow paragraphs in the title hence `\\` is forbidden.

Doesn't work:
```
\title{WORCS: A Workflow for Open Reproducible Code in Science \\
Version: 0.1.2, date: 28 May, 2020} 
```
Works:
```
\title{WORCS: A Workflow for Open Reproducible Code in Science \newline
Version: 0.1.2, date: 28 May, 2020} 
```

**Comment by cjvanlissa** [comment]
You can use vertical bars to add newlines to the Rmd YAML:

title: |
| First line
| Second line

**Comment by aaronpeikert** [comment]
I can confirm that this worcs for standard `pdf_document` but it doesn't work for me with `papaja::apa6_pdf`:

I get this error:
```
! Argument of \@sect has an extra }.
<inserted text> 
                \par 
l.154 
```
with
```
title: |
    | WORCS: A Workflow for Open Reproducible Code in Science
    | `r paste0("Version: ", worcs:::cran_version(), ", date: ", format(Sys.Date(), "%d %b,\ %Y"))`
```
but this compiles without complaint:
```
title: |
    | WORCS: A Workflow for Open Reproducible Code in Science \newline
    `r paste0("Version: ", worcs:::cran_version(), ", date: ", format(Sys.Date(), "%d %b,\ %Y"))`
```

**Comment by brandmaier** [comment]
Thanks. That did the trick. I commited the fix in my latest PR.
