### ISSUE TITLE
Discussion: Title

### ISSUE THREAD

**Issue by brandmaier** [cjvanlissa/worcs#68]
There were already some discussions on the title. I agree it should not narrow down to a particular discipline but what about emphasising the "Open Science" mission by rearranging from

> WORCS: A Workflow for Open Reproducible Code in Science

to

> WORCS: A Workflow for  Reproducible Code in Open Science

**Comment by cjvanlissa** [comment]
WRCOS? It's a bit late to change the acronym ;)

**Comment by brandmaier** [comment]
Haha! Sorry, I completely forgot about that!!! I am just going to shut up and close this comment.
