### ISSUE TITLE
Code Ocean and Digital Ocean

### ISSUE THREAD

**Issue by brandmaier** [cjvanlissa/worcs#74]
In the manuscript, we mention _digital ocean,_ which I just realized I had been mixing up with _code ocean_. In an earlier paper, we used the cloud computing platform Code Ocean (here is the reproducible container: https://codeocean.com/capsule/0325493/tree/v1). I believe those two services are not the same and not even related? Should we also mention code ocean?

**Comment by cjvanlissa** [comment]
Crap. You are right. I kept getting redirected to digital ocean when I was googling, so I assumed that they had a name change. I've submitted the manuscript, but will fix in the preprint tomorrow.

**Comment by aaronpeikert** [comment]
Should I change that tomorrow?

**Comment by cjvanlissa** [comment]
Addressed by d5c21b2

**Comment by aaronpeikert** [comment]
Did you know that if you include `closes #74` in the commit message it gets automatically referenced and closed (if merged into master)?
