### ISSUE TITLE
jss style

### ISSUE THREAD

**Issue by aaronpeikert** [cjvanlissa/worcs#77]
I know to late but anyway, the rticles package has a jss template:
` rticles::jss_article()`

**Comment by cjvanlissa** [comment]
I used it!

Dr. Caspar J. van Lissa
Assistant professor of developmental data science, FSW ambassador to the Open Science Community Utrecht<http://www.openscience-utrecht.com/>
Utrecht University, dept. Methodology & Statistics
Sjoerd Groenmangebouw C1.19, 3584CH Utrecht, the Netherlands. Secretariat: +31 30 253 4438
[cid:image001.jpg@01D63A62.D3C298C0]

**Comment by aaronpeikert** [comment]
Oh sorry, I skimmed the diff between the jobs branch and master but must hab overlooked it.
