### ISSUE TITLE
The link to cos_prereg does not seem to work.

### ISSUE THREAD

**Issue by joph** [cjvanlissa/worcs#78]
When clicking on the link on cos_prereg in the documentation pdf, the pdf-reader jumps back to the start of the document:
https://github.com/cjvanlissa/worcs/blob/fdbb8c1d2332fb9eb33b26f0b29a0dc4f9cec598/man/worcs_project.Rd#L39

**Comment by cjvanlissa** [comment]
This is expected behavior; links across packages only work within R.

**Comment by cjvanlissa** [comment]
Addressed here; this is intended behavior by CRAN: https://stackoverflow.com/questions/32897418/when-documenting-a-with-code-linkpackage-avoid-a-link-to-nowhere-in-the-pdf
