### ISSUE TITLE
Link to init does not work

### ISSUE THREAD

**Issue by joph** [cjvanlissa/worcs#79]
When clicking on the link on init, the pdf reader starts back to the start of the document: 
https://github.com/cjvanlissa/worcs/blob/fdbb8c1d2332fb9eb33b26f0b29a0dc4f9cec598/man/worcs_project.Rd#L48

**Comment by cjvanlissa** [comment]
As far as I can tell, this is expected behavior: The links work when accessing documentation as HTML in R, but not in the pdf versions. See, for example, this package documentation: https://cran.r-project.org/web/packages/prereg/prereg.pdf
