### ISSUE TITLE
Rename 'indices' to 'derived variables'

### ISSUE THREAD

**Issue by brandmaier** [cjvanlissa/worcs#81]
In the preregistration template, we have measured variables, manipulated variables and indices. To increase clarity, I suggest to rename "indices" to "derived variables".

**Comment by cjvanlissa** [comment]
@brandmaier these templates are not generated by `worcs`, they originate in the `prereg` package (and I believe they are based on the official forms of these platforms)

**Comment by brandmaier** [comment]
Sure. Thanks, @cjvanlissa!
