### ISSUE TITLE
Discussion: prepare_data.R

### ISSUE THREAD

**Issue by brandmaier** [cjvanlissa/worcs#82]
I am currently test-driving the package and after several test runs, I feel that "prepare_data.R" may not be an optimal name. It may suggest that it's run as part of the whole pipeline to generate results whereas it's really only run once to import the data into a WORCS project, right? What about naming it "import_data.R" then? I am curious about your thoughts.

**Comment by aaronpeikert** [comment]
So your issue is that `prepare_data.R` comes before open_/closed_data and hence does not represent the whole data preparation?

The real question is, how much have people "todo" before they should call open_/closed_data?

If it is really just one import call I think we should eliminate the whole file and replace it with `closed_data(haven::read_sav())`. However, if there is more to do then *just* importing the data, then I think import_data is not suited as a name :smile:

**Comment by bvreede** [comment]
Another take: this is actually one of my favorite parts of worcs. It
separates the data cleaning step from the rest of the analysis, which is a
good practice in data science. It is naïve to assume that for most people
loading data will really be as simple as a read_csv. In fact, various data
cleaning steps may need to be performed, steps to ensure
anonymization/pseudonymization, or really anything else that needs to
happen before the data is ready for analysis. By explicitly including the
prepare_data script you allow a user to disconnect anything having to do
with data cleaning from the rest of the analysis. The script will be saved,
but the original data will not.

(ps responding via email from my phone for the first time; I hope this
works :))

**Comment by aaronpeikert** [comment]
This email responding works :mailbox_with_mail:

 I think @brandmaier and I are completly in agreement about the importance of the data cleaning step and this is exactly the issue @brandmaier has with the solution. The name `prepare_data` suggests that the whole data cleaning process is in that script, but the documentation/comment in the template suggests that this is **not** the case.

**Comment by cjvanlissa** [comment]
I agree with Barbara that `import_data()` is too restrictive. It's also possible to overthink this; the purpose of this file is well documented, and unless there is clear evidence that it is being misapplied, I don't see an urgent need to change it. It is "good enough" AFAIK

**Comment by brandmaier** [comment]
Thanks, Barbara. I totally agree with you. I think the procedure is great and absolutely useful. I don't want to change this, at all. I think I was trying to argue from the perspective of the scope of a WORCS project. The WORCS project is like a box, in which I can put all my project-related files. So, getting the data from my local drive into the project could also be labeled as an "import", which underlines that the R file, which does the job, is run only once and not everytime the manuscript is built.

**Comment by brandmaier** [comment]
I don't have a strong opinion. I am happy as long as we agree that we chose the simplest and most concise label.

**Comment by cjvanlissa** [comment]
I hear you Andreas, but I think Aaron has the right take here. If the only purpose is to import, you don't need `prepare_data.R`; just run `closed_data(haven::read_sav())`. If you need to do more than just import, you'd use `prepare_data.R`, and in this case, a name like `import_data()` would not cover the content of the script.

**Comment by aaronpeikert** [comment]
I think it is quit possible that I misunderstood @cjvanlissa / the documentation :eyes: 

Should the whole data preprocessing be in `prepare_data.R`?

**Comment by aaronpeikert** [comment]
Related Question:
Should data preprocessing happen before or after `closed_/open_data`?

**Comment by cjvanlissa** [comment]
@aaronpeikert no, only the part that cannot be publically shared.

**Comment by aaronpeikert** [comment]
OK then I think `prepare_data` doesn't quite cut it for me.
I expect that such file prepares the data for the analysis, but this file prepares the data for publishing?

**Comment by aaronpeikert** [comment]
But anyhow I think we can leave it as it is. I find it a bit confusing, but as you said its well documented.

**Comment by aaronpeikert** [comment]
My confusion comes from the different expectation about what for the data should be prepared.
The goal of the prepare_data script is to generate a `data.csv` right?
So what about `prepare_csv.R`?

**Comment by cjvanlissa** [comment]
ALright guys, I think we should park this discussion for a bit ;) @bvreede and I have a first course teaching this material in 3 weeks, we'll see how the participants get on with it.

**Comment by brandmaier** [comment]
Sorry for stealing your time. This is just my excitement about the project.

**Comment by bvreede** [comment]
The email responding may work, but fully grasping the issue from a phone screen while chasing a 4yo does not ;)

I understood `prepare_data` to be about preprocessing, indeed; not just about importing. That results in 1. a data file that is part of the `worcs` package and will be shared as such (either masked or not), and 2. a file that is prepared for the analysis that will be part of the manuscript. And in the current scope, that concerns a .csv, but one option for enhancement could be that different kinds of files can be considered, so by restricting the name to `prepare_csv.R` I fear you may shoot yourself in the foot.

If anything, this discussion shows we agree, but may need to clarify things even more in the documentation?

Ack - in the time I typed this the issue has already received more comments and even been closed; guys, it's hard to keep up with you, for real! :) I'm posting this anyway, hope that is OK. Not to get the last word in, but more not to lose my thoughts (which are fragmented as it is... *sigh*).

YES @cjvanlissa let's see what the participants do!

**Comment by cjvanlissa** [comment]
I think that, after this discussion, we should consider renaming `participants` to `subjects`...

**Comment by bvreede** [comment]
🤣
