### ISSUE TITLE
open_data only saves files in main WORCS project directory  

### ISSUE THREAD

**Issue by aschetti** [cjvanlissa/worcs#85]
Hi,
today I followed Barbara and Caspar's [worcshop](https://github.com/bvreede/worcshop), which inspired me to try out `worcs` for one of my projects. The package is awesome! Unfortunately, I encountered a problem when trying to save data as _.csv_ after preprocessing. Below a minimal reproducible example:

``` r

# Load packages ----------------------------------------------------------

library(worcs)
#> [0;34mWelcome to WORCS: Workflow for Open Reproducible Code in Science. Please read the tutorial before using this package, and consider citing it:
#>   Van Lissa and colleagues (2020) <doi:10.17605/OSF.IO/ZCVBS>[0m
library(here)
#> here() starts at /tmp/RtmpblO83e/reprex3cf81f92f09b

# Generate data ----------------------------------------------------------

data_reprex <-
  data.frame(
    x = rnorm(100, mean = 0, sd = 1),
    y = rnorm(100, mean = 1, sd = 1)
  )

# Save data and codebook ----------------------------------------------------------

open_data(
  data_reprex,
  filename = "data_reprex.csv",
  codebook = "codebook_reprex.Rmd",
  worcs_directory = here("reprex/")
)
#> Warning in basename(path): restarting interrupted promise evaluation
#> Warning in normalizePath(worcs_directory): path[1]="/tmp/RtmpblO83e/
#> reprex3cf81f92f09b/reprex/": No such file or directory
#> Error in value[[3L]](cond): No '.worcs' file found in this directory or any of its parent directories; either this is not a worcs project, or the working directory is not set to the project directory.
```
<sup>Created on 2020-07-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Contrary to what `reprex` would have you believe, there is no error and all files (`codebook_reprex.csv`, `codebook_reprex.html`, `codebook_reprex.md`, `codebook_reprex.Rmd`, `data_reprex.csv`) are saved. However, they end up in the main WORCS project directory instead of the `reprex` subfolder.

Could you please help debug?

Thanks,
Antonio

**Comment by cjvanlissa** [comment]
Dear Antonio, as a jumping off point: I'm 99% sure this is due to the use of the `here` package, and possibly due to the fact that you pass an unevaluated promise to open_data when you say `worcs_directory = here("reprex/")`.

This argument should be a character string, either an absolute or relative file path.

I'm not sure if you need `here` with worcs; worcs determines its own main directory recursively in a similar way to the here package.

**Comment by aaronpeikert** [comment]
> you pass an unevaluated promise to open_data when you say worcs_directory = here("reprex/")
I am not sure that is really what is going on.
First, I am certain that `here()` returns an absolute path as character. 

Still, I tested forcing the evaluation of all arguments, but this doesn't change anything:

``` r
open_data <- function(data, filename = "data.csv", codebook = "codebook.Rmd", worcs_directory = ".", ...){
  Args <- c(as.list(environment()), list(...))
  Args$open <- TRUE
  do.call(save_data, Args)
}
```
Then I asserted that here() really just returns a path (`stopifnot(is.character(worcs_dir))`):

``` r
library(worcs)
#> [0;34mWelcome to WORCS: Workflow for Open Reproducible Code in Science. Please read the tutorial before using this package, and consider citing it:
#>   Van Lissa and colleagues (2020) <doi:10.17605/OSF.IO/ZCVBS>[0m
library(here)
#> here() starts at /tmp/RtmpY6oWEK/reprex65e72d7d38a9
# Generate data ----------------------------------------------------------

data_reprex <-
  data.frame(
    x = rnorm(100, mean = 0, sd = 1),
    y = rnorm(100, mean = 1, sd = 1)
  )

worcs_dir <- here("reprex")
stopifnot(is.character(worcs_dir))

open_data(
  data_reprex,
  filename = "data_reprex.csv",
  codebook = "codebook_reprex.Rmd",
  worcs_directory = worcs_dir
)
#> Warning in basename(path): restarting interrupted promise evaluation
#> Warning in normalizePath(worcs_directory): path[1]="/tmp/RtmpY6oWEK/
#> reprex65e72d7d38a9/reprex": No such file or directory
#> Error in value[[3L]](cond): No '.worcs' file found in this directory or any of its parent directories; either this is not a worcs project, or the working directory is not set to the project directory.
```
Finally I realized that the directories and files in the reprex just do not exist!

``` r
dir.create(here("reprex"))
file.create(here("reprex", ".worcs"))
#> [1] TRUE
open_data(
  data_reprex,
  filename = "data_reprex.csv",
  codebook = "codebook_reprex.Rmd",
  worcs_directory = worcs_dir
)
#> [0;32mv  [0m[0;30mStoring original data in 'data_reprex.csv' and updating the checksum in '.worcs'.[0m
#> [0;32mv  [0m[0;30mUpdating '.gitignore'.[0m
#> processing file: codebook_reprex.Rmd
#> output file: codebook_reprex.knit.md
#> 
#> Preview created: codebook_reprex.html
#> 
#> Output created: codebook_reprex.md
```

<sup>Created on 2020-07-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

So I think there is nothing wrong with using `here()` (ok, in fact I love it myself), but that `worcs` doesn't catch that the directory / .worcs file doesn't exists.
@cjvanlissa Should I open a PR to give an informative error?

**Comment by aaronpeikert** [comment]
@aschetti Thank you for providing a reprex, without it I wouldn't have looked into this!

**Comment by cjvanlissa** [comment]
@aaronpeikert  thank you for diving into this so thoroughly! Of course, I would appreciate a pr. Any idea as to why the directory did not exist?

**Comment by aaronpeikert** [comment]
For why the directory did not exist, that is simply a user error. The reprex runs in a temporary directory, so there are only folders that you create in the reprex.

**Comment by cjvanlissa** [comment]
Gotcha.

**Comment by aschetti** [comment]
Thanks @cjvanlissa and @aaronpeikert ! I might have missed your proposed solution/workaround but, based on your previous messages, I tried the following:

```
worcs_dir <- here("reprex")

open_data(
  data_reprex,
  filename = "data_reprex.csv",
  codebook = "codebook_reprex.Rmd",
  worcs_directory = worcs_dir
)
```

```
open_data(
  data_reprex,
  filename = "data_reprex.csv",
  codebook = "codebook_reprex.Rmd",
  worcs_directory = "/home/aschetti/Documents/Projects/WORCS_TOJ_invalid/reprex"
)
```
In both cases, the behavior is the same: all files are saved in the main WORCS project directory instead of the intended subdirectory. This happens regardless of `reprex`, so any possible user errors are not the cause. So, it's not `reprex` and it's not `here`. If I understood correctly, @aaronpeikert plans a PR with informative message, but how can this issue be solved?

Thanks again for your help!

**Comment by aaronpeikert** [comment]
Sorry, it is only now that I see what you are trying to archive. This should do the trick:

``` r
library(here)
#> here() starts at /tmp/RtmpUS9KiH/reprex9ad93f90ead2
library(worcs)
#> [0;34mWelcome to WORCS: Workflow for Open Reproducible Code in Science. Please read the tutorial before using this package, and consider citing it:
#>   Van Lissa and colleagues (2020) <doi:10.17605/OSF.IO/ZCVBS>[0m
data_reprex <-
  data.frame(
    x = rnorm(100, mean = 0, sd = 1),
    y = rnorm(100, mean = 1, sd = 1)
  )

# Save data and codebook ----------------------------------------------------------
dir.create(here("mydata"))
file.create(here(".worcs"))
#> [1] TRUE
file.create(here("mydata", ".worcs"))
#> [1] TRUE
message(here(".worcs"))
#> /tmp/RtmpUS9KiH/reprex9ad93f90ead2/.worcs

open_data(
  data_reprex,
  filename = "mydata/data_reprex.csv",
  codebook = "codebook_reprex.Rmd")
#> [0;32mv  [0m[0;30mStoring original data in 'mydata/data_reprex.csv' and updating the checksum in '.worcs'.[0m
#> [0;32mv  [0m[0;30mUpdating '.gitignore'.[0m
#> processing file: codebook_reprex.Rmd
#> output file: codebook_reprex.knit.md
#> 
#> Preview created: codebook_reprex.html
#> 
#> Output created: codebook_reprex.md
```

<sup>Created on 2020-07-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Please close if it now worcs :) for you (mind the relative path in filename).

**Comment by aschetti** [comment]
Hi @aaronpeikert ,
thanks again for your quick reply! Based on your suggestion above, I hard-coded the folder path in the `filename` and `codebook` args. The updated code looks like this:

```
open_data(
  data_reprex,
  filename = "reprex/data_reprex.csv",
  codebook = "reprex/codebook_reprex.Rmd"
)
```
This correctly saves all files into the `reprex` subfolder (nested into the main WORCS project directory). This is an effective workaround for this specific case, but I guess it would be better to have a more generalizable solution, e.g., by allowing to change path in the `worcs_directory` arg. I wish my coding skills were good enough to submit a PR with the solution but, alas, this is not the case.

Anyway, many thanks for your help. I will now close this issue.
