### ISSUE TITLE
Data size limit

### ISSUE THREAD

**Issue by swvanderlaan** [cjvanlissa/worcs#91]
I work with large-scale genetic datasets (GWAS). The analyses are done outside R, but eventually summary statistics are generated, see below. This contains a couple of columns per genetic variant (`MarkerName` in this case), and anywhere between 1 million to 10 or 20 million rows. 

GWAS data is not special in that sense, the row is some data of some identifier (`MarkerName`) of interest. There of course other large-scale datasets - the `iris` dataset could also contain 15 million rows instead of 150.

Can `WORCS` this size? If not: I think it would be worthwhile to invest in this to make it more versatile. Perhaps R scripts that 'control' python scripts for managing the large datasets. In the end visualisation could easily be done in R - I think. 

Happy to help and work on this. 

Best,

Sander

Example dataset

> MarkerName	Allele1	Allele2	Freq1	FreqSE	MinFreq	MaxFreq	Effect	StdErr	P-value	Direction	HetISq	HetChiSq	HetDf	HetPVal
> rs2326918	a	g	0.8460	0.0058	0.8330	0.8546	0.0019	0.0401	0.963	+--+--++-+	0.0	4.757	9	0.855
> rs7929618	c	g	0.1403	0.0187	0.1206	0.1750	-0.0653	0.0556	0.2406	??---?+-+-	0.0	2.656	6	0.8507
> rs66941928	t	c	0.7943	0.0082	0.7837	0.8230	0.0538	0.0426	0.2068	-++-++++++	0.0	1.375	9	0.998
> rs146253013	t	c	0.0103	0.0000	0.0103	0.0103	-0.9435	0.6709	0.1596	????????-?	0.0	0.000	0	1

**Comment by cjvanlissa** [comment]
Note that you can supply any function to synthesize data using the arguments below (see documentation). For huge datasets, you should choose an appropriate and computationally feasible function.

`model_expression = ranger(x = x, y = y)
  predict_expression = predict(model, data = xsynth)$predictions`

**Comment by swvanderlaan** [comment]
Ah yes. So it should work probably with a large GWAS summary statistics dataset. I will just try it out and see what's practical and report back.
