### ISSUE TITLE
manuscript styles

### ISSUE THREAD

**Issue by swvanderlaan** [cjvanlissa/worcs#92]
I followed the tutorial https://www.youtube.com/watch?v=uzjpN_yFeUU, but chose 'elsevier_article', and user license CC_BY-NC-4.0, yet no manuscript template is made. Is this normal? 

Thanks

**Comment by swvanderlaan** [comment]
Ah, I now see the message `X  Could not generate an APA6 manuscript file, because the 'papaja' package is not installed. Run this code to see instructions on how to install this package from GitHub:`.

Gonna install and report back!

**Comment by swvanderlaan** [comment]
Ah, that was not it. When selecting `elsevier_article`, regardless of license or preregistration, the manuscript files are not made. How to fix this?

**Comment by cjvanlissa** [comment]
I don't think this is correct.. it works fine here, and in tests. Please provide a reproducible example

**Comment by swvanderlaan** [comment]
It turns out it probably has to do with installment issues. Seems to be solved.
