### ISSUE TITLE
Make it possible to manually add a synthetic dataset

### ISSUE THREAD

**Issue by cjvanlissa** [cjvanlissa/worcs#94]
Should it be possible to call closed_data() without synthesizing data?
It should definitely be possible to manually add a synthetic dataset.

**Comment by aaronpeikert** [comment]
I imagine it could be helpful to call `closed_data()` without synthesizing if-then `load_data()` would issue a message about how to obtain the real data. Or maybe we build a new function that does that (called `private_data()` or `requestable_data()`)?

**Comment by cjvanlissa** [comment]
I agree. I ran into the following issues recently:
1) A lavaan model did not converge on the synthetic data, thus rendering the remainder of my code non-reproducible. The problem was solved by simulating data from the lavaan model directly - but there was no function to replace the synthetic_data.csv
2) Data were too large to be synthesized using random forests. Simple bootstrapping per column would work, and synthetic() allows for this - but closed_data() does not allow users to modify the call to synthetic()

**Comment by aaronpeikert** [comment]
Ah I didn't read carefully enough! Couldn't you pass the dots from `closed_data` to `save_data` and from there to `synthetic()`?

**Comment by aaronpeikert** [comment]
I would do this for you, but I do not understand the magic of [`all_args()`](https://github.com/cjvanlissa/worcs/blob/81de33ff6dc6163af19ee11540d235d606de893c/R/misc.R#L61-L89)

**Comment by cjvanlissa** [comment]
@aaronpeikert I added all_args() to avoid problems with list(match.call()[-1]) where, for example, in tests, functions would fail because the passed object were within some higher parent environment and not within scope for the final function down the call stack.
