### ISSUE TITLE
disclaimer in paper: results based on synthetic vs. original data

### ISSUE THREAD

**Issue by aschetti** [cjvanlissa/worcs#98]
During the awesome [WORCShop at the Open Science Community Rotterdam](https://www.openscience-rotterdam.com/2020/10/worcshop-oct2020/), I mentioned to @cjvanlissa that it could be useful to have a disclaimer in the paper specifying whether the reported results are generated from the synthetic data set. This would avoid possible misunderstandings, e.g., users fail to numerically reproduce some results based on original data because they are using the synthetic data.

Would that make sense?

**Comment by cjvanlissa** [comment]
@aschetti working on this, but I need to hash out a potential bug in Rmarkdown first.
